### ISSUE TITLE
Have you ever considered a scaffold CLI tool?

### ISSUE THREAD

**Issue by kasumi9863** [kokororin/Kotori.php#4]
Hello!

I have been trying your framework recently, and I found it not only awesome but very easy to use. I think that there should be a scaffold CLI tool, for example like **vue-cli**, for the new user to build a Kotori.php project and so on.

So, I have tried to build a extremely simple scaffold CLI tool for this framework. Currently, this scaffold can build a pure project, modify project config easily, generate some core files and other simple actions.

Here is the project: https://github.com/kasumi9863/kotori-php-cli/

( It is the first time that I have made a CLI tool, so this tool may have some bugs, but I will try my best to improve it. )

Hope you can take this into considerations : )

(PS: Your framework is quite excellent, keep on going! :+1: )

**Comment by kokororin** [comment]
Awesome, Thank you! PRs are welcomed
